#!/usr/bin/env python3
"""Generate the pool of unique pouch instance classes.

The pouches are kits of Enhanced First Aid Kits, which keeps contents per class name: every pouch
type ships one prototype plus a pool of concrete classes inheriting from it, and a prototype a
player picks up is swapped for a free one. See Enhanced First Aid Kits' tools/generate_instances.py
for the whole story.

Usage:  python tools/generate_instances.py
"""

import io
import os

# Keep in sync with EUP_INSTANCES_PER_POUCH in addons/main/script_macros.hpp
INSTANCES_PER_POUCH = 300

POUCHES = ["eup_UtilityPouch", "eup_AmmoPouch", "eup_AmmoBag", "eup_EngineerBag", "eup_CBRNBag"]

HEADER = """// AUTO-GENERATED by tools/generate_instances.py - do not edit by hand.
// One concrete class per pouch instance, see the script for the why.
"""

TEMPLATE = (
    'class {kit}_{i}: {kit} {{'
    'scope = 1; scopeCurator = 0; ace_arsenal_hide = 1; ace_arsenal_uniqueBase = "{kit}"; '
    'EFAK_prototype = 0; EFAK_instanceId = {i};'
    '}};'
)

OUT = os.path.join(os.path.dirname(__file__), "..", "addons", "pouches", "CfgWeapons_instances.hpp")


def main():
    lines = [HEADER]
    for kit in POUCHES:
        lines.append("// %s instances" % kit)
        for i in range(1, INSTANCES_PER_POUCH + 1):
            lines.append(TEMPLATE.format(kit=kit, i=i))
        lines.append("")
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print("wrote %s (%d classes)" % (os.path.normpath(OUT), len(POUCHES) * INSTANCES_PER_POUCH))


if __name__ == "__main__":
    main()
